version: "3.9"
# define various services
services:
  flask:
    platform: linux/x86_64
    build: ./
    image: suriyadeepan/docker-secrets
    ports:
      - 5001:5000
    restart: "no"
    secrets:
      - secure_key

secrets:
  secure_key:
    file: private_key.txt
