version: "3.9"
# define various services
services:
  nginx-custom:
    build: ./nginx-custom/
    ports:
      - 80:80
    restart: "no"
    depends_on:
      - photogram
  photogram:
    build: ./
    image: photogram:latest
    ports:
      - 5000:5000
    restart: "no"
    secrets:
      - secure_key
      - config_file

secrets:
  secure_key:
    file: secret.json
  config_file:
    file: config.json
